TownMangerWebUI/Controllers/ResdientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TownManger.Domain.Abstract;
using TownManger.Domain.Entities;
using TownMangerWebUI.Models;

namespace TownMangerWebUI.Controllers
{
    public class ResdientController : Controller
    {
        // GET: Resdient

        public IResdientRepository repository;


        public ResdientController(IResdientRepository resdientRepository)
            {
            this.repository = resdientRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        //public ViewResult List(string Building, int page = 1)
        //{
        //    ResdientViewModel model = new ResdientViewModel
        //    {
        //        Resdient = repository.Resdients.Where(p => Building == null || p.Category == category).OrderBy(p => p.ProductID)
        //    .Skip((page - 1) * PageSize).Take(PageSize),
        //        PagingInfo = new PagingInfo
        //        {
        //            CurrentPage = page,
        //            ItemsPerPage = PageSize,
        //            //TotalItems = repository.Products.Count()
        //            TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(e => e.Category == category).Count()
        //        },
        //        CurrentCategory = category
        //    };
        //    return View(model);
        //}



        public FileContentResult GetImage(int resdientID)
        {
            Resdient resdient = repository.Resdients.FirstOrDefault(p => p.ResdientID == resdientID);
            if (resdient != null)
            {
                return File(resdient.ImageData, resdient.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
    
}

TownMangerWebUI/Views/Admin/BuildingFloorUnit.cshtml
@model IEnumerable<TownManger.Domain.Entities.Floor>

@{
    ViewBag.Title = "FloorsIndexforBuilding";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Floors for Building @ViewBag.BuildingName</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>

                <th class="text-center">Floor Name</th>
                <th class="text-center">Unit Numbers</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var p in Model)
            {
                <tr>
                    @Html.HiddenFor(m => p.FloorID)
                    <td class="text-center">@Html.Label(p.FloorName)</td>
                    <td class="text-center" style="font-size:larger">@Html.Label(p.UnitNumbers.ToString())</td>
                    <td class="text-center">
                        @Html.ActionLink("Edit", "UnitFloorIndex", new{p.FloorID},
                               new { @class = "btn btn-default" })

                    </td>

                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back", "BuildingManageIndex", null,
        new { @class = "btn btn-default" })
    </div>


</div>

TownMangerWebUI/Views/Admin/BuildingIndex.cshtml
@model IEnumerable <TownManger.Domain.Entities.Building>

@{
    ViewBag.Title = "BuildingIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Buildings</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th class="text-center">Building ID</th>
                <th class="text-center">Building Name</th>
                <th class="text-center">Floor Numbers</th>
                <th class="text-center">Actions</th>
            </tr>

            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.BuildingID</td>
                        <td class="text-center">@Html.ActionLink(item.BuildingName, "EditBuilding", new { item.BuildingID })</td>
                        <td class="text-center" style="font-size:larger">@Html.ActionLink(item.FloorNumbers.ToString(), "FloorIndex", new { item.BuildingID })</td>
                        <td class="text-center">
                            @using (Html.BeginForm("DeleteBuilding", "Admin"))
                            {
                                @Html.Hidden("buildingID", item.BuildingID)
                                <input type="submit"
                                       class="btn btn-default btn-xs"
                                       value="Delete" />
                            }
                        </td>

                    </tr>
                }
            }




        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back", "Index", null,
        new { @class = "btn btn-default" })
        <span class="pull-right">
            @Html.ActionLink("Add a new Building", "CreateBuilding", null,
                new { @class = "btn btn-success" })
        </span>
    </div>


    </div>

TownMangerWebUI/Views/Admin/BuildingManageIndex.cshtml
@model IEnumerable<TownManger.Domain.Entities.Building>

@{
    ViewBag.Title = "BuildingIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Buildings</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
                <th class="text-center" style="color:#115b86">Building Name</th>
                <th class="text-center" style="color:#115b86">Floor Numbers</th>
                <th class="text-center" style="color:#115b86">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center" style="font-size:larger;font-family:Consolas">@Html.LabelForModel(item.BuildingName)</td>
                    <td class="text-center" style="font-size:larger">@Html.LabelForModel(item.FloorNumbers.ToString())</td>
                    <td class="text-center">
                        @using (Html.BeginForm("BuildingFloorUnit", "Admin"))
                        {
                            @Html.Hidden("buildingID", item.BuildingID)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Edit Units" />
                        }
                    </td>

                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back", "BuildingIndex", null,
        new { @class = "btn btn-default" })
       
    </div>


</div>

TownMangerWebUI/Views/Admin/EachFloor.cshtml
@model TownManger.Domain.Entities.Floor


@using (Html.BeginForm("EditFloorUnits", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 

<tr>
        @Html.HiddenFor(m => m.FloorID)
    <td>@Html.TextBoxFor(m => Model.FloorName)</td>
    <td>@Html.TextBoxFor(m => Model.UnitNumbers)</td>
    <td>
        <input type="submit"
               class="btn btn-default btn-xs"
               value="Save" />
    </td>

</tr>
}

TownMangerWebUI/Views/Admin/EditBuilding.cshtml
@model TownManger.Domain.Entities.Building

@{
    ViewBag.Title = "EditBuilding";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    @if (Model.BuildingID == 0)
    {
        <div class="panel-heading">

            <h3>Create New Building</h3>

        </div>




     using (Html.BeginForm("EditBuilding", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
     {
     <div class="panel-body">
          <div class="form-group">

               @Html.HiddenFor(m => m.BuildingID)
                    @*@Html.ValidationSummary()*@
                    <div class="form-group">
                        <label>Building Name :</label>
                        @Html.TextBoxFor(m => m.BuildingName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Floor Numbers:</label>
                        @Html.TextBoxFor(m => m.FloorNumbers, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Number Of Units for each floor:</label>
                        @Html.TextBoxFor(m => m.UnitNumberFloor, new { @class = "form-control" })
                    </div>
          </div>

     </div>
     <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel and return to List", "BuildingIndex", null, new { @class = "btn btn-default" })

     </div>
     }





  }
    else
    {
        <div class="panel-heading">

            <h3>Edit Building @Model.BuildingName</h3>

        </div>




        using (Html.BeginForm("EditBuilding", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                <div class="form-group">

                    @Html.HiddenFor(m => m.BuildingID)
                    @*@Html.ValidationSummary()*@
                    <div class="form-group">
                        <label>Building Name :</label>
                        @Html.TextBoxFor(m => m.BuildingName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Floor Numbers:</label>
                        @Html.TextBoxFor(m => m.FloorNumbers, new { @class = "form-control" , @disabled = "disabled" })
                    </div>
                    <div class="form-group">
                        <label>Number Of Units for each floor:</label>
                        @Html.TextBoxFor(m => m.UnitNumberFloor, new { @class = "form-control", @disabled = "disabled" })
                    </div>
                </div>










            </div>





            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel and return to List", "BuildingIndex", null, new { @class = "btn btn-default" })

            </div>
        }


    }


</div>

TownMangerWebUI/Views/Admin/EditFloorUnits.cshtml
@model TownManger.Domain.Entities.Floor

@{
    ViewBag.Title = "EditFloorUnits";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel-heading">
    <h2>EditFloorUnits</h2>
</div>


<div class="panel">

        @using (Html.BeginForm("EditFloorUnits", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                <div class="form-group">

                    @Html.HiddenFor(m => m.FloorID)
                    @Html.HiddenFor(m => m.BuildingID)

                    @*@Html.ValidationSummary()*@
                    <div class="form-group">
                        <label>Building Name :</label>
                        @Html.TextBoxFor(m => m.FloorName, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label>UnitNumbers:</label>
                        @Html.TextBoxFor(m => m.UnitNumbers, new { @class = "form-control" })
                    </div>
                </div>
            </div>





            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel and return to List", "FloorIndex", null, new { @class = "btn btn-default" })

            </div>
          }
</div>

TownMangerWebUI/Views/Admin/FloorIndex.cshtml
@model IEnumerable<TownManger.Domain.Entities.Floor>

@{
    ViewBag.Title = "FloorsIndexforBuilding";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Floors for Building @ViewBag.BuildingName</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>

                <th class="text-center">Floor Name</th>
                <th class="text-center">Unit Numbers</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var p in Model)
            {<tr>
                @Html.HiddenFor(m=>p.FloorID)
                <td class="text-center">@Html.Label(p.FloorName)</td>
                <td class="text-center" style="font-size:larger">@Html.Label(p.UnitNumbers.ToString())</td>
                <td class="text-center">
                 @Html.ActionLink("Edit", "EditFloorUnits", new{p.FloorID},
                        new { @class = "btn btn-default" })

                </td>

</tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back", "BuildingIndex", null,
        new { @class = "btn btn-default" })
    </div>


</div>

TownMangerWebUI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row panel">
    @Html.RouteLink("Create Buildings", new { Controller = "admin", Action = "BuildingIndex" }, new { @class = "btn btn-block btn-default btn-lg" })
    @Html.RouteLink("Create Building Units", new { Controller = "admin", Action = "CreateBuildingUnits" }, new { @class = "btn btn-block btn-default btn-lg" })
    @Html.RouteLink("Design Units", new { Controller = "admin", Action = "BuildingManageIndex" }, new { @class = "btn btn-block btn-default btn-lg" })
    @Html.RouteLink("Resdients", new { Controller = "admin", Action = "ResdientIndex" }, new { @class = "btn btn-block btn-default btn-lg" })

    @Html.RouteLink("Register Resdient", new { Controller = "admin", Action = "CreateResdient" }, new { @class = "btn btn-block btn-default btn-lg" })
    @Html.RouteLink("Register Family Members", new { Controller = "admin", Action = "CreateResdient" }, new { @class = "btn btn-block btn-default btn-lg" })

</div>

TownMangerWebUI/Views/Admin/ResdientEdit.cshtml
@model TownManger.Domain.Entities.Resdient

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="panel">
    <div class="panel-heading">
        @if (Model.ResdientID == 0)
        {
            <h3>Create New Resdient</h3>

        }
        else
        {
            <h3>Edit @Model.ResdientName</h3>

        }




    </div>
    @using (Html.BeginForm("ResdientEdit", "Admin",FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="panel-body">
        @Html.HiddenFor(m => m.ResdientID)
        <div class="form-group">
            <label>National ID :</label>
            @Html.TextBoxFor(m => m.NID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Full Name:</label>
            @Html.TextBoxFor(m => m.ResdientName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Mobile:</label>
            @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>FamilyRelationship:</label>
            @Html.TextBoxFor(m => m.FamilyRelationship, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Car Number:</label>
            @Html.TextBoxFor(m => m.CarNumber, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Building Name:</label>
           
                @Html.DropDownList("BuildingID",null, "---Select Building---",  htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">

            <label>Floor Number:</label>
            @Html.DropDownList("FloorID", null, "---Select Floor---", htmlAttributes: new { @class = "form-control" })

        </div>
        <div class="form-group">
            <label>Unit Number:</label>
            @Html.DropDownList("UnitID", null, "---Select Unit---", htmlAttributes: new { @class = "form-control" })

        </div>

        <div class="form-group">
            <div style="position:relative;">
                <label>Image</label>
                <a class='btn btn alert-warning' href='javascript:; '>
                    Choose File...
                    <input type="file" name="Image" id="select" size="40"
                           style="position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0); opacity:0;background-color:transparent;color:transparent;">
                </a>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
            @if (Model.ImageData == null)
            {
                <img class="img-thumbnail" width="150" height="150" id=" imaged"
                     src="~/images/noImage.jpg" />
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150" id=" imaged"
                     src="@Url.Action("GetImage", "Resdient",new { Model.ResdientID })" />
            }
        </div>





    </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new {
            @class = "btn btn-default"
            })
        </div>
    }
</div>

<script>
  
    $(document).ready(function () {

       


            $("#BuildingID").change(


                function () {
                   
                
                $.get("/Admin/GetFloorBuildingDrop", { buildingID: $("#BuildingID").val() }, function (data) {
                    $("#FloorID").empty();
                    $.each(data, function (index, row) {
                        $("#FloorID").append("<option value='" + row.Value + "'>" + row.Text + "</option>")
                        $("#FloorID").val("Select")
              
                        
                        
                    });

                    
                   
                });

            })
        });


     $(document).ready(function () {
        $("#FloorID").change(function () {
            $.get("/Admin/GetUnitFloorDrop", { floorID: $("#FloorID").val() }, function (data) {
                $("#UnitID").empty();
                $.each(data, function (index, row) {
                    $("#UnitID").append("<option value='" + row.Value + "'>" + row.Text + "</option>")
                    $("#UnitID").val("Select")

                });
            });
        })
    });


           

    
  

   
    
</script>
        
        
        
       

TownMangerWebUI/Views/Admin/ResdientIndex.cshtml
@model  IEnumerable< TownManger.Domain.Entities.Resdient>

@{
    ViewBag.Title = "Admin : All Resdients";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    @*<div class="panel-heading">
            <h3>All Resdients</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th class="text-right">ID</th>
                    <th>Name</th>
                    <th class="text-right">Unit Number</th>
                    <th class="text-center">Actions</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-right">@item.ResdientID</td>
                        <td>@Html.ActionLink(item.ResdientName, "ResdientEdit", new { item.ResdientID })</td>
                        <td class="text-right">
                        @Html.DisplayFor(m => item.Unit.UnitID)</td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("resdientID", item.ResdientID)
                                <input type="submit"
                                       class="btn btn-default btn-xs"
                                       value="Delete" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>*@

 
    @foreach (var p in Model)
    {
        @Html.Partial("ResdientSummry", p)
    }
    <div class="panel-footer">
        @Html.ActionLink("Add a new Resdient", "CreateResdient", null,
        new { @class = "btn btn-default" })
    </div>
</div>

TownMangerWebUI/Views/Admin/ResdientSummry.cshtml
@model TownManger.Domain.Entities.Resdient

<div class="well" >
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Admin",new { Model.ResdientID })" />
            </div>
    }
    <h3>
        <strong>@Model.ResdientName</strong>
        <span class="pull-right">
            @Html.ActionLink("  Edit  ", "ResdientEdit", new { Model.ResdientID }, new { @class = "btn btn-success" })
        </span>

    </h3>


   
    <div class="pull-right">

        @using (Html.BeginForm("Delete", "Admin"))
        {
            @Html.Hidden("resdientID", Model.ResdientID)
            <input type="submit"
                   class="btn btn-danger"
                   value="Delete" />
        }
    </div>

    <span class=" label label-primary"style="font-size:15px">Building  @Model.BuildingID</span>
 
    <span class=" label label-primary"style="font-size:15px">Unit Number : @Model.UnitID</span>

</div>

TownMangerWebUI/Views/Admin/UnitFloorEdit.cshtml
@model TownManger.Domain.Entities.Unit

@{
    ViewBag.Title = "UnitFloorEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel-heading">
    <h2>Edit Units</h2>
</div>


<div class="panel">

    @using (Html.BeginForm("UnitFloorEdit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            <div class="form-group">

                @Html.HiddenFor(m => m.FloorID)
                @Html.HiddenFor(m => m.UnitID)

                @*@Html.ValidationSummary()*@
                <div class="form-group">
                    <label>Unit Number :</label>
                    @Html.TextBoxFor(m => m.UnitNumber, new { @class = "form-control"});
                </div>

                <div class="form-group">
                    <label>Building Name :</label>
                    @Html.TextBoxFor(m => m.BuildingID, new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div class="form-group">
                    <label>Family Name :</label>
                    @Html.TextBoxFor(m => m.FamilyID, new { @class = "form-control" })
                </div>
            </div>
        </div>





        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "UnitFloorIndex", new { Model.FloorID }, new { @class = "btn btn-default" })

        </div>
    }
</div>

TownMangerWebUI/Views/Admin/UnitFloorIndex.cshtml
@model IEnumerable<TownManger.Domain.Entities.Unit>

@{
    ViewBag.Title = "UnitFloorIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Units for Floor @ViewBag.FloorName</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
                <th class="text-center">Unit ID</th>
                <th class="text-center">Unit Number</th>
                <th class="text-center">Building Name</th>
                <th class="text-center">Family Name</th>

                <th class="text-center">Actions</th>
            </tr>
            @foreach (var unit in Model)
            {
                <tr>
                    <td class="text-center">@unit.UnitID</td>

                    <td class="text-center">@unit.UnitNumber</td>
                    <td class="text-center" style="font-size:larger">@unit.BuildingID</td>
                    <td class="text-center" style="font-size:larger">@unit.FamilyID</td>

                    <td class="text-center">
                        @Html.ActionLink("Edit", "UnitFloorEdit", new{unit.UnitID},
                               new { @class = "btn btn-default" })

                    </td>

                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back", "BuildingManageIndex", null,
        new { @class = "btn btn-default" })
    </div>


</div>